"""TikTok discovery engine: search -> candidate creator profiles -> Mongo.

Also owns the browser session (login/checkpoint detection) and the payload
parsing (TikTokUser + friends): both are produced here first and re-used by
analysis_engine.py, which imports them rather than redefining them, so
there is exactly one definition of each across the two files.

WHY THIS DRIVES A REAL BROWSER RATHER THAN CALLING AN API DIRECTLY
    TikTok publishes no free, stable public API for search or profile
    lookup. Every "TikTok API" advertised online is either a paid reseller
    wrapping the same scraping this module does, or a raw replication of
    TikTok's own private request signing (X-Bogus, msToken, _signature),
    generated by TikTok's own JavaScript at runtime from browser
    fingerprinting, and changed on TikTok's own schedule, not ours.
    Reverse-engineering that signature is exactly the "breaks without
    warning every few months" maintenance burden every OTHER platform in
    this engine avoids by driving a real logged-in browser instead and
    letting the platform's own frontend do the signing for us (see
    stealth/browser.py). TikTok gets the same treatment here, not a
    different one.

WHERE THE DATA ACTUALLY COMES FROM, IN ORDER
    1. TikTok server-renders its own initial page state into a `<script>`
       tag on every page, `__UNIVERSAL_DATA_FOR_REHYDRATION__` on current
       builds, `SIGI_STATE` on older ones/behind experiments. A profile
       page's user info AND a search page's first batch of results both
       arrive this way, in the SAME response as the HTML, no XHR race to
       wait on. This is the primary source, and deliberately mirrors the
       hard lesson already learned in instagram/analysis_engine.py: passive
       network interception of a payload that may not fire reliably is not
       something to build the primary path around.
    2. Network responses matching TikTok's own `/api/search/...` calls,
       intercepted passively while scrolling, the second page of results
       onward arrives this way, since the hydration script only ever
       carries the first batch.
    3. When both of the above come up empty. TikTok strips the hydration
       payload from traffic its own bot-scoring doesn't like, leaving a
       skeleton page with no counts, this falls back to reading the
       rendered results directly: anchors linking to `/@<username>`, the
       one thing a results page cannot hide, since a clickable result IS a
       link to a profile.

NEEDS LIVE VERIFICATION. Every field name below (`uniqueId`, `avatarLarger`,
`followerCount`, ...) is reverse-engineered from public write-ups, not
captured from a live authenticated session the way every other platform's
parsing in this codebase was. The DOM fallback and the run_strategies chain
exist specifically so a wrong guess here degrades to fewer fields rather
than to zero results reported as a clean success, but this module should
not be trusted in production before a real session confirms it end to end
(see registry.py's `stability_note` for this platform).
"""

from __future__ import annotations

import asyncio
import json
import re
import sys
import time
import weakref
from contextlib import asynccontextmanager
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Iterator, Optional
from urllib.parse import quote

from backend.config.settings import settings
from backend.shared.extraction import ExtractionResult, run_strategies
from backend.shared.logging import get_logger
from backend.shared.models.row import Row
from backend.shared.text import iter_dicts
from backend.stealth.browser import Session

log = get_logger("tiktok")

# Session / login state
# The upload page requires a logged-in account. TikTok redirects anyone
# without one to /login, so it doubles as a clean authenticated probe the
# same way Instagram's /accounts/edit/ does. `expect_path` is the positive
# confirmation (see stealth/browser.py::Session.check_session's own
# docstring on why absence of a login string is not evidence of success).
UPLOAD_PROBE = "https://www.tiktok.com/upload?lang=en"

RE_LOGIN = re.compile(r"(Log in to TikTok|Sign up for TikTok|Use QR code to log in)", re.I)
RE_CHECKPOINT = re.compile(
    r"(verify to continue|select.{0,20}shapes|drag the slider|slide to verify|"
    r"unusual (login )?activity|security check|captcha)",
    re.I,
)
RE_GONE = re.compile(
    r"(couldn.t find this account|this account can.t be found|user doesn.t exist)", re.I,
)

# A REGION WHERE TIKTOK IS BLOCKED serves the same government notice for
# every URL and redirects to `/<region>/about`. Confirmed live (2026-08-23,
# an Indian IP, no proxy): `tiktok.com/search?q=...` landed on
# `https://www.tiktok.com/in/about` with the June 2020 India ban notice,
# zero `/api/search/` responses, an empty hydration payload and no profile
# links in the DOM.
#
# Worth naming rather than letting it fall through: with no search response
# and nothing in the DOM, the sweep reported "results never rendered" and
# `stopped=stalled` -- indistinguishable from a parser break or a slow
# render, and it sends whoever investigates at the extraction code when the
# actual fix is to route this platform through a proxy. Same reasoning as
# facebook/discovery_engine.py's deny_paths note.
RE_GEOBLOCK = re.compile(
    r"(decided to block|Government of India|Govt\. of India"
    r"|not available in your (country|region))", re.I,
)


def geoblocked(page_url: str, body: str) -> bool:
    """WHAT: is this page the region-blocked notice rather than the page we
    asked for? HOW: the redirect is the primary signal -- landing on an
    `/<cc>/about` path when a different path was requested is something
    only the block does -- with the notice text as corroboration for a
    future variant that does not redirect. LINKED TO: checked by
    Discovery.sweep() and by analysis_engine.py::Scraper.process(), both of
    which stop early and say so rather than reporting an empty result."""
    if re.search(r"/[a-z]{2}/about\b", page_url or "", re.I):
        return True
    return bool(RE_GEOBLOCK.search(body or ""))


class TikTokSession(Session):
    """WHAT: a logged-in TikTok browser session. HOW: everything is
    inherited from stealth/browser.py::Session; only the liveness probe is
    platform-specific. LINKED TO: constructed by analysis_engine.py's
    Scraper, and by sessions/manager.py when it verifies stored cookies."""

    async def check_session(self) -> bool:  # type: ignore[override]
        """WHAT: are these cookies still logged in? HOW: loads the upload
        page, which redirects a logged-out visitor away, and confirms the
        browser actually LANDED on /upload rather than merely receiving a
        200 from a login wall. Returning the base implementation's verdict
        keeps the conclusive-vs-inconclusive contract every platform
        shares (see stealth/browser.py): False means the cookies are
        genuinely rejected, while a network failure raises instead, so
        sessions/manager.py never quarantines a good session over a
        blip."""
        return await super().check_session(
            UPLOAD_PROBE, RE_LOGIN, RE_CHECKPOINT, expect_path="/upload",
        )


# Payload parsing (profile extraction)


def _to_int(v: Any) -> Optional[int]:
    """Loose numeric coercion, counts arrive as either ints or strings
    depending on which of TikTok's own JSON shapes a given response uses."""
    if v is None:
        return None
    try:
        return int(v)
    except (TypeError, ValueError):
        return None


@dataclass
class TikTokUser:
    """WHAT: one TikTok account, normalised out of whichever JSON dialect
    it arrived in. HOW: a single flat record that both of TikTok's own
    response shapes (camelCase video-author nodes and snake_case
    user-card nodes) are parsed INTO by user_from_node, so nothing
    downstream has to know which dialect a given account came from.
    LINKED TO: analysis_engine.py::Scraper.fill maps this onto a Row;
    `match_kind` is what discovery_service.py surfaces as
    discovery_source."""

    entity_id: str = ""
    username: str = ""
    nickname: str = ""
    avatar: str = ""
    bio: str = ""
    bio_link: str = ""
    verified: bool = False
    private: bool = False
    follower_count: Optional[int] = None
    following_count: Optional[int] = None
    # total likes across every video. TikTok's own reach figure, the
    # closest analogue another platform's follower count plays for "how far
    # could this impersonation spread"
    heart_count: Optional[int] = None
    video_count: Optional[int] = None
    last_post_iso: str = ""
    # "account" = TikTok surfaced this as a NAME MATCH for the query (its
    # own user-card block); "author" = it merely posted a video the query
    # matched. Only the first kind is what impersonation triage is looking
    # for, and the two arrive mixed together in one response -- see
    # iter_users. Analysts see this as the profile's discovery_source.
    match_kind: str = "author"

    @property
    def url(self) -> str:
        """The canonical profile URL, or "" for a record with no handle
        (which is unusable as a hit -- sweep() filters those out)."""
        return f"https://www.tiktok.com/@{self.username}" if self.username else ""

    @property
    def has_custom_pic(self) -> bool:
        """TikTok omits the avatar entirely for a default-picture account
        rather than serving a known stock URL, so presence IS the signal.
        That is why this platform needs no RE_DEFAULT_PIC equivalent."""
        return bool(self.avatar)


def user_to_row(u: "TikTokUser", keyword: str, *, source: str = "search") -> Row:
    """A `TikTokUser` -> the shared `Row` record `Sweep.hits` now carries.

    `user_from_node()` already parses follower_count/bio/verified/avatar
    straight out of TikTok's own search response -- the same fields
    `analysis_engine.py::Scraper.fill` copies onto a Row after a second
    visit. Carrying them here means analysis no longer starts from a blank
    Row for a field this sweep already read. `heart_count` (total likes
    across every video, TikTok's own reach figure) rides along as
    `friends` for lack of a more specific slot -- TikTok has no
    following-count analogue worth a field of its own.

    `row.target` is seeded from the raw search term (`keyword`); a caller
    that resolves keyword-plan parents should overwrite it before scoring.
    """
    row = Row(
        url=u.url, target=keyword, entity_type="profile",
        profile_id=u.entity_id or u.username, username=u.username,
        profile_name=u.nickname or u.username,
        profile_pic_url=u.avatar, has_custom_pic=u.has_custom_pic,
        verified=u.verified, followers=u.follower_count, friends=u.heart_count,
        bio=u.bio,
    )
    for f in ("profile_name", "profile_pic_url", "verified"):
        row.mark(f, f"discovery-search:{source}")
    for f in ("followers", "friends", "bio"):
        if getattr(row, f) not in (None, ""):
            row.mark(f, f"discovery-search:{source}")
    return row


def _avatar_url(*candidates: Any) -> str:
    """TikTok hands avatars over in two shapes depending on which of its
    own JSON dialects a response uses: a bare URL string (the camelCase
    hydration/`author` shape) or a dict carrying a `url_list` (the
    snake_case `user_info` shape). Take the first usable one."""
    for c in candidates:
        if isinstance(c, str) and c:
            return c
        if isinstance(c, dict):
            urls = c.get("url_list") or c.get("urlList")
            if isinstance(urls, list):
                for u in urls:
                    if isinstance(u, str) and u:
                        return u
    return ""


def user_from_node(user: dict, stats: Optional[dict] = None) -> Optional[TikTokUser]:
    """One `user`-shaped dict (+ its sibling `stats`/`statsV2` dict, if
    counts live separately rather than merged into `user` itself) ->
    TikTokUser."""
    if not isinstance(user, dict):
        return None
    username = user.get("uniqueId") or user.get("unique_id") or ""
    if not username:
        return None
    stats = stats if isinstance(stats, dict) else {}

    def stat(*keys: str) -> Optional[int]:
        """First usable count under any of `keys`, looked for in the
        sibling stats dict before the user dict. Several spellings are
        tried per field because the two dialects name them differently
        (see the LIVE-CONFIRMED note below)."""
        for src in (stats, user):
            for k in keys:
                if k in src:
                    n = _to_int(src[k])
                    if n is not None:
                        return n
        return None

    raw_bio_link = user.get("bioLink") or {}
    bio_link = raw_bio_link.get("link", "") if isinstance(raw_bio_link, dict) else str(raw_bio_link or "")

    # LIVE-CONFIRMED (2026-08-18): TikTok's search response mixes two
    # dialects of the same record. Video authors arrive camelCase
    # (`uniqueId`, `avatarLarger`, `followerCount`, `verified`); the
    # user-card block that carries actual name matches arrives snake_case
    # (`unique_id`, `avatar_thumb` as a url_list dict, `follower_count`,
    # `total_favorited`, and verification as a non-empty `custom_verify` /
    # `enterprise_verify_reason` string rather than a bool). Reading only
    # the camelCase spelling is what silently dropped every name match --
    # for "reliance" that meant discarding `reliance`, `reliance163` and
    # `re1iance` (a digit-swap impersonation) while keeping twelve
    # unrelated creators who happened to mention the word.
    verified = bool(
        user.get("verified")
        or (user.get("custom_verify") or "").strip()
        or (user.get("enterprise_verify_reason") or "").strip()
    )

    return TikTokUser(
        entity_id=str(user.get("id") or user.get("uid") or user.get("secUid") or user.get("sec_uid") or ""),
        username=username,
        nickname=(user.get("nickname") or "").strip(),
        avatar=_avatar_url(
            user.get("avatarLarger"), user.get("avatarMedium"), user.get("avatarThumb"),
            user.get("avatar_larger"), user.get("avatar_medium"), user.get("avatar_thumb"),
        ),
        bio=(user.get("signature") or "").strip(),
        bio_link=bio_link.strip(),
        verified=verified,
        private=bool(user.get("privateAccount") or user.get("secret") or user.get("private_account")),
        follower_count=stat("followerCount", "follower_count", "followers"),
        following_count=stat("followingCount", "following_count", "following"),
        heart_count=stat("heartCount", "total_favorited", "heart", "diggCount"),
        video_count=stat("videoCount", "aweme_count", "video_count"),
    )


def iter_users(blob: Any) -> Iterator[TikTokUser]:
    """Every user-shaped node in a hydration/search payload, deduped by
    username. Walks the whole tree rather than trusting one fixed path,
    see this module's docstring on the key layout already having moved
    once.

    NAME MATCHES COME FIRST. A search response carries two populations
    that look alike structurally but mean opposite things for
    impersonation triage:

      * `user_list[].user_info` nodes (TikTok's own `type: 4` user-card
        block) -- accounts it considers a match for the QUERY. These are
        the impersonation candidates.
      * `author` nodes hanging off video items -- whoever happened to post
        a clip the query matched. Overwhelmingly irrelevant here: a
        "reliance" search returns a dozen unrelated creators who said the
        word.

    Both are yielded, since a real impersonator does also post videos, but
    accounts are yielded first so `rank` (and therefore the order an
    analyst reviews cards in) puts genuine name matches at the top instead
    of burying one behind twelve creators.
    """
    accounts: list[TikTokUser] = []
    authors: list[TikTokUser] = []
    seen: set[str] = set()

    def take(u: Optional[TikTokUser], bucket: list[TikTokUser]) -> None:
        """Add a parsed user to its bucket unless that handle was already
        taken."""
        if u and u.username.lower() not in seen:
            seen.add(u.username.lower())
            bucket.append(u)

    # TWO PASSES over the tree, not one -- account nodes and author nodes
    # are NOT grouped together in TikTok's own JSON, they're interleaved in
    # whatever order the search response happens to render them. A single
    # walk that dedupes into `seen` as it goes only gives "accounts win"
    # when an account's own user_info node HAPPENS to come before that same
    # user's video-author node in the raw tree -- if a video by the real
    # account is listed before the account's own card (routine: TikTok's
    # results are ranked, not grouped by node type), `take()` claims that
    # username into `authors` first, and the account-card node reached
    # later is silently dropped as "already seen." A single walk cannot
    # fix this by reordering the check -- the account card genuinely
    # hasn't been read yet at that point in the tree. Walking for accounts
    # ONLY, in full, before authors are ever considered is what actually
    # guarantees "the stronger classification wins" regardless of raw
    # JSON order.
    for d in iter_dicts(blob):
        info = d.get("user_info")
        if isinstance(info, dict) and (info.get("unique_id") or info.get("uniqueId")):
            u = user_from_node(info)
            if u:
                u.match_kind = "account"
            take(u, accounts)

    for d in iter_dicts(blob):
        if isinstance(d.get("user_info"), dict):
            continue  # already handled as a possible account node above
        nested = d.get("user")
        if isinstance(nested, dict) and (nested.get("uniqueId") or nested.get("unique_id")):
            stats = d.get("stats") if isinstance(d.get("stats"), dict) else d.get("statsV2")
            take(user_from_node(nested, stats if isinstance(stats, dict) else None), authors)
        elif d.get("uniqueId") or d.get("unique_id"):
            take(user_from_node(d), authors)

    yield from accounts
    yield from authors


def viewer_username(blob: Any) -> str:
    """The logged-in account's own handle, per the page's app context.

    LIVE-CONFIRMED (2026-08-18): every rendered TikTok page embeds the
    VIEWER at `__DEFAULT_SCOPE__["webapp.app-context"].user.uniqueId`, and
    the sidebar renders an `a[href="/@<viewer>"]` link. Both sit inside
    exactly the surfaces this module harvests, so before this the session's
    own account was collected as a discovered "impersonator" of every
    keyword, on every sweep, ranked first (it is in the hydration payload,
    which is read before any search response arrives). It appeared in zero
    /api/search/ payloads and in 5 of 5 DOM reads -- it is page chrome, not
    a result.
    """
    try:
        scope = blob.get("__DEFAULT_SCOPE__", {}) if isinstance(blob, dict) else {}
        user = (scope.get("webapp.app-context") or {}).get("user") or {}
        return str(user.get("uniqueId") or user.get("unique_id") or "")
    except Exception:
        return ""


def profile_from(blob: Any, username: str = "") -> Optional[TikTokUser]:
    """The one user node in a payload matching `username`, or the first
    user node at all when no username is given to match against."""
    want = username.lower()
    for u in iter_users(blob):
        if not want or u.username.lower() == want:
            return u
    return None


# TikTok video ids are Snowflake-style: the top 32 bits are a Unix
# timestamp (seconds) of when the video was created, a documented,
# independently reproducible property of the id itself, unlike everything
# else in this module that depends on guessing a JSON key name correctly.
def _video_id_to_iso(video_id: Any) -> str:
    """WHAT: a video id -> the ISO date it was created. HOW: shifts the
    top 32 bits out of the Snowflake-style id (see the note above) and
    sanity-bounds the result to [TikTok's 2016 launch, now] -- a stamp
    outside that window means the value was not a video id at all, and
    reporting nothing beats reporting a date from 1974. LINKED TO:
    newest_post_iso() below; analysis_engine.py uses it as the free,
    no-extra-navigation tier of its last-post chain."""
    try:
        ts = int(video_id) >> 32
    except (TypeError, ValueError):
        return ""
    try:
        dt = datetime.fromtimestamp(ts, tz=timezone.utc)
    except (ValueError, OSError, OverflowError):
        return ""
    now = datetime.now(timezone.utc)
    # TikTok launched in 2016; a decoded stamp outside [launch, now] means
    # this wasn't actually a video id (or the id scheme assumption doesn't
    # hold for it), report nothing rather than a nonsense date
    return dt.date().isoformat() if 2016 <= dt.year and dt <= now else ""


def _epoch_to_iso(ts: Any) -> str:
    """A `createTime` value (real epoch seconds, straight off TikTok's own
    search JSON) -> ISO date, with the same launch-date/future sanity
    bounds as `_video_id_to_iso`."""
    n = _to_int(ts)
    if not n:
        return ""
    try:
        dt = datetime.fromtimestamp(n, tz=timezone.utc)
    except (ValueError, OSError, OverflowError):
        return ""
    now = datetime.now(timezone.utc)
    return dt.date().isoformat() if 2016 <= dt.year and dt <= now else ""


def newest_post_iso(blob: Any, username: str = "") -> str:
    """The newest video's date for one profile, decoded straight from its
    id (see `_video_id_to_iso`), deliberately not read off any "createTime"
    field, since that key's presence/name in TikTok's own JSON is far less
    certain than the id-encodes-a-timestamp property. Scoped to `username`
    when a video's author is identifiable, unscoped (best candidate found
    anywhere in the blob) otherwise, a hydration payload for one profile
    page should not carry any other author's videos, but this stays
    defensive rather than assuming that."""
    want = username.lower()
    best = ""
    for d in iter_dicts(blob):
        vid = d.get("id")
        if not vid or not isinstance(vid, (str, int)):
            continue
        # a video node's own shape: an author reference somewhere alongside
        # its id, OR (search/list contexts) a sibling "desc"/"video" field
        author = d.get("author")
        author_name = ""
        if isinstance(author, dict):
            author_name = (author.get("uniqueId") or "").lower()
        elif isinstance(author, str):
            author_name = author.lower()
        if want and author_name and author_name != want:
            continue
        if "desc" not in d and "video" not in d and "stats" not in d:
            continue  # not actually a video node, just something with an "id" key
        iso = _video_id_to_iso(vid)
        if iso and iso > best:
            best = iso
    return best


# Hydration script (primary source)

JS_HYDRATION = """
() => {
  const ids = ['__UNIVERSAL_DATA_FOR_REHYDRATION__', 'SIGI_STATE'];
  for (const id of ids) {
    const el = document.getElementById(id);
    if (el && el.textContent) return el.textContent;
  }
  return '';
}
"""


async def read_hydration(page) -> Any:
    """The page's own embedded initial-state JSON, or None when it's
    missing/unparseable, never raises, callers fall through to
    interception/DOM either way."""
    try:
        text = await page.evaluate(JS_HYDRATION)
    except Exception:
        return None
    if not text:
        return None
    try:
        return json.loads(text)
    except (json.JSONDecodeError, ValueError):
        return None


# DOM fallback
# Anchored on links to `/@<username>`, which is what a clickable search
# result IS regardless of anything else TikTok changes about the response
# shape or the surrounding markup, the same reasoning Facebook's own DOM
# fallback documents for anchoring on profile links there.
JS_DOM_SEARCH = """
() => {
  const seen = new Set();
  const out = [];
  for (const a of document.querySelectorAll('a[href^="/@"]')) {
    const href = a.getAttribute('href') || '';
    const m = href.match(/^\\/@([^/?]+)/);
    if (!m) continue;
    const username = m[1];
    if (seen.has(username.toLowerCase())) continue;
    seen.add(username.toLowerCase());
    const card = a.closest('div') || a;
    const img = a.querySelector('img') || card.querySelector('img');
    let name = '';
    for (const el of card.querySelectorAll('p, span, h3, h4')) {
      const t = (el.textContent || '').trim();
      if (t && t.toLowerCase() !== username.toLowerCase() && !t.startsWith('@')) { name = t; break; }
    }
    out.push({ username, name, avatar: img ? (img.getAttribute('src') || '') : '' });
  }
  return out;
}
"""


async def dom_users(page) -> list[TikTokUser]:
    """Scrape the rendered results feed. Used only when neither the
    hydration script nor an intercepted search response yielded anything.
    See Discovery.sweep."""
    rows = await page.evaluate(JS_DOM_SEARCH)
    users: list[TikTokUser] = []
    for r in rows or []:
        username = (r.get("username") or "").strip()
        if not username:
            continue
        users.append(TikTokUser(
            username=username,
            nickname=(r.get("name") or "").strip(),
            avatar=(r.get("avatar") or "").strip(),
        ))
    return users


def parse_lines(text: str) -> Iterator[Any]:
    """Most responses are a single JSON object; some stream as JSON lines."""
    text = (text or "").strip()
    if not text:
        return
    try:
        yield json.loads(text)
        return
    except (json.JSONDecodeError, ValueError):
        pass
    for line in text.splitlines():
        line = line.strip()
        if line.startswith("{"):
            try:
                yield json.loads(line)
            except (json.JSONDecodeError, ValueError):
                continue


# Crawling / pagination

SEARCH_URL = "https://www.tiktok.com/search?q={q}"

# THE USERS TAB IS UNREACHABLE, AND REACHING IT MAKES RESULTS WORSE.
#
# An earlier revision landed on `/search?q=...` (the Top tab) and then
# clicked the in-page "Users" tab, on the theory that only a direct
# deep-link to `/search/user?q=...` tripped bot detection. Re-verified
# against a real logged-in session on 2026-08-18, that is no longer true,
# and the click never actually worked in the first place:
#
#   * The selector looked for `[role="tab"]` / any element whose text is
#     "Users". TikTok's search tab strip is `div#search-tabs` holding plain
#     `<button>`s -- no role, no data-e2e. The ONLY `[role="tab"]` nodes on
#     the page belong to the notifications panel ("All activity", "Likes",
#     ...). So the click landed on the inner `<span>`, which does not
#     switch tabs. Discovery has therefore always been reading the Top tab.
#   * Clicking the real button DOES switch (the URL becomes
#     `/search/user?q=...`) -- and that is strictly worse. The resulting
#     `/api/search/user/full/` call returns HTTP 200 with a ZERO-BYTE body,
#     the panel renders "Something went wrong", and the rendered results
#     collapse from 13 accounts to 1. A reload reproduces it exactly. The
#     request carries msToken and X-Bogus but no `_signature`; this is
#     TikTok soft-blocking the endpoint, not a timing or selector problem,
#     and no amount of clicking fixes it.
#
# So: stay on the Top tab, deliberately. It is the surface that actually
# answers, and it carries BOTH populations -- TikTok's own user-card block
# (`type: 4`, real name matches) and video authors -- which `iter_users`
# now separates and ranks. See that function.

async def newest_post_via_search(ctx, username: str, timeout_s: float = 20.0) -> str:
    """The one CAPTCHA-free way found to learn when an account last posted.

    Visiting a profile's OWN video grid to find this out repeatedly put
    the session behind TikTok's slide-verify challenge, the grid tiles
    render as empty placeholders, no `/api/post/item_list/` response ever
    carries a body, and this backend will never automate solving that
    challenge (out of scope on principle, not just difficulty). Searching
    the account's own username is the SAME search surface
    `Discovery.sweep` already uses successfully, and never triggered the
    challenge across repeated live testing, likely because it's an
    ordinary keyword search, not a deep-link into one account's own
    content feed. TikTok's search response carries a real `createTime`
    (epoch seconds) directly on each video node, no id-decoding needed.

    STAYS ON THE TOP TAB, deliberately. An earlier revision tried to click
    through to the "Videos" tab first. That click never actually worked
    (same `[role="tab"]` selector defect as the Users tab -- it clicked an
    inert `<span>`), and this function only ever worked BECAUSE of that:
    it listens for `/api/search/general/full/`, which is the Top tab's own
    response. Re-verified live on 2026-08-18, genuinely reaching the
    Videos tab is worse, not better -- the URL becomes `/search/video?q=`
    and its `/api/search/item/full/` call returns HTTP 200 with a
    ZERO-BYTE body, exactly like the Users tab. So the click is gone
    rather than "fixed": repairing that selector would have silently
    broken last-post detection for every TikTok profile.

    NOT exhaustive: this is whatever TikTok's search ranks as relevant for
    the username as a query, not a full chronological listing of the
    account's posts, a thin/generic username may surface nothing even
    for an active account. A miss here is "this weaker signal didn't
    happen to find anything," never "confirmed inactive", callers must
    treat "" the same as any other unknown, not as evidence of dormancy.
    """
    if not username:
        return ""
    page = await ctx.new_page()
    responses: list[str] = []

    async def on_response(resp):
        """Collects the search response bodies as the page fires them.
        Filtered to the one endpoint that carries `createTime`, since this
        page is only being visited to read a real post date."""
        if "/api/search/general/full" not in resp.url:
            return
        try:
            responses.append(await resp.text())
        except Exception:
            pass

    page.on("response", lambda r: asyncio.create_task(on_response(r)))
    try:
        await page.goto(
            SEARCH_URL.format(q=quote(username)), wait_until="domcontentloaded",
            timeout=int(timeout_s * 1000),
        )
        # Wait for the results view itself rather than a flat sleep -- the
        # response this reads only fires once it renders.
        try:
            await page.wait_for_selector("#search-tabs button", timeout=int(timeout_s * 1000))
        except Exception:
            pass
        await page.wait_for_timeout(4000)

        want = username.lower()
        best_ts = 0
        for text in responses:
            for blob in parse_lines(text):
                for d in iter_dicts(blob):
                    author = d.get("author")
                    author_name = (author.get("uniqueId") or "").lower() if isinstance(author, dict) else ""
                    if author_name != want:
                        continue
                    ts = _to_int(d.get("createTime"))
                    if ts and ts > best_ts:
                        best_ts = ts
        return _epoch_to_iso(best_ts) if best_ts else ""
    except Exception:
        return ""
    finally:
        try:
            await page.close()
        except Exception:
            pass


# TikTok's search results do NOT scroll the window. They live inside
# `<main id="grid-main">`, an inner overflow container: the document itself
# stays exactly one viewport tall (scrollHeight == innerHeight == 864,
# window.scrollY pinned at 0 no matter what). So
# `window.scrollTo(0, document.body.scrollHeight)` -- and `End`, and even a
# mouse wheel -- moved nothing, TikTok's lazy-loader was never triggered,
# and every sweep stopped after the single page that arrives with the
# initial render. It then reported `stalled`, which looks identical to
# "the results genuinely ran out" from the outside. It is not: scrolling
# the real container walks the cursor 12 -> 132 across 11 pages and ends
# on the payload's own `has_more: 0`, i.e. actual exhaustion.
#
# Measured live for "reliance": 15 users before, 135 after (9x), same
# session, same query, same time budget (~53s).
#
# Falls back to the window scroll when no inner container owns the
# overflow, so a future layout that does scroll the document still works.
JS_SCROLL_RESULTS = """
() => {
  const el = document.querySelector('#grid-main')
    || Array.from(document.querySelectorAll('div, main, section')).find(e => {
         const st = getComputedStyle(e);
         return /(auto|scroll)/.test(st.overflowY) && e.scrollHeight > e.clientHeight + 40;
       });
  if (el) { el.scrollTop = el.scrollHeight; return true; }
  window.scrollTo(0, document.body.scrollHeight);
  return false;
}
"""


# ── the Users tab ────────────────────────────────────────────────────────
#
# This is the surface impersonation triage actually wants. Searching
# "gautam adani" here returns @gautam.adani33, @realgautamadani,
# @gautam.adani1, @gautamadami ... -- accounts wearing the name. The Top
# tab (Discovery.sweep) structurally cannot see them: its payload is video
# items, with a small user-card rider that is often absent entirely.
#
# Getting in meant isolating what TikTok gates on. Verified live
# (2026-08-18) that it is NOT any of the obvious candidates -- in every one
# of these the answer is HTTP 200 with a ZERO-BYTE body and a "Something
# went wrong" panel:
#   * the tab selector      clicking the real #search-tabs button navigates
#                           to /search/user?q= correctly
#   * headless              headful behaves identically
#   * request signing       a warmed context sends X-Dynosaur, X-Gnarly,
#                           X-Bogus, msToken, device_id and odinId -- the
#                           same set the working request carries
#   * being logged in       an anonymous context is refused just the same
#   * search_id ordering    waiting for the Top results first changes nothing
#
# What it gates on is the BROWSER CONTEXT TYPE. Playwright's ordinary
# `launch()` + `new_context()` -- an incognito-style context, which is what
# stealth/browser.py::Session uses -- is refused indefinitely.
# `launch_persistent_context()` against a real on-disk profile directory is
# answered normally: 23KB of JSON, ten accounts, byte-identical to what a
# human sees. Confirmed headless, and on a brand-new profile directory, so
# this needs neither a display nor a warm-up period.
#
# Deliberately ANONYMOUS: no pooled cookies are loaded. The endpoint does
# not want them (it answers a logged-out browser perfectly well), and not
# sending them means this pass cannot burn the logged-in session that
# analysis depends on.
#
# Additive and non-fatal by construction: any failure here degrades
# discovery to the Top-tab results it had before, never fails the job.
USER_SEARCH_URL = "https://www.tiktok.com/search/user?q={q}"

# `launch_persistent_context` takes an exclusive lock on the profile
# directory, and sweeps run concurrently (DiscoveryOptions.concurrency),
# so two keywords reaching this at once would collide. One at a time.
# Created per running loop, not once at import: a module-level
# asyncio.Lock binds to the first loop that touches it and then raises
# "Event loop is closed" in every later one. Production runs a single
# loop, so this stays invisible there -- it surfaced as one flaky test,
# which is exactly the cheap warning worth heeding. Keyed weakly so a
# finished loop does not keep its lock alive.
_PROFILE_LOCKS: "weakref.WeakKeyDictionary" = weakref.WeakKeyDictionary()


async def _body_text(page) -> str:
    """The page's visible text, or "" if it cannot be read. Used by the
    geo-block check, where an unreadable body must not itself raise."""
    try:
        return await page.inner_text("body")
    except Exception:
        return ""


def _profile_lock() -> asyncio.Lock:
    """The lock guarding the persistent profile directory, for THIS event
    loop (see the note above for why it cannot be a module-level lock).
    LINKED TO: taken by anonymous_context(); Discovery._merge_user_accounts
    deliberately skips re-taking it when the sweep already holds it."""
    loop = asyncio.get_running_loop()
    lock = _PROFILE_LOCKS.get(loop)
    if lock is None:
        lock = _PROFILE_LOCKS[loop] = asyncio.Lock()
    return lock


def _profile_dir():
    """Where the persistent browser profile lives. Under the same
    configured blob path as every other session artefact, so one setting
    moves them all."""
    return settings.session_blob_path / "tiktok-profile"


@asynccontextmanager
async def anonymous_context(proxy: Optional[dict] = None):
    """A credential-free TikTok browser context, on a persistent profile.

    BOTH halves matter and both are load-bearing:

    * PERSISTENT. Playwright's ordinary `launch()` + `new_context()` (an
      incognito-style context, which is what stealth/browser.py::Session
      uses) is refused by TikTok -- blank pages, zero-byte API responses.
      `launch_persistent_context` against a real on-disk profile is served
      normally. This is the single difference that unlocked the Users tab.
    * ANONYMOUS. TikTok's account search answers a logged-out browser
      perfectly, and profile analysis reads every field it normally reads.
      Sending no cookies means a sweep cannot burn the pooled session, and
      cannot be stopped by that session expiring.

    Serialised on `_profile_lock()`: the profile directory takes an
    exclusive OS lock, so two of these at once would collide.
    """
    from playwright.async_api import async_playwright

    from backend.stealth.fingerprint import LAUNCH_ARGS, chrome_binary
    from backend.stealth.proxy import build_proxy_config

    profile = _profile_dir()
    profile.mkdir(parents=True, exist_ok=True)

    launch: dict[str, Any] = {"headless": settings.headless, "args": LAUNCH_ARGS}
    if binary := chrome_binary():
        launch["executable_path"] = binary
    if proxy and (cfg := build_proxy_config(proxy)):
        launch["proxy"] = cfg

    async with _profile_lock():
        pw = ctx = None
        try:
            pw = await async_playwright().start()
            ctx = await pw.chromium.launch_persistent_context(str(profile), **launch)
            await _warm(ctx)
            yield ctx
        finally:
            if ctx is not None:
                try:
                    await ctx.close()
                except Exception:
                    pass
            if pw is not None:
                try:
                    await pw.stop()
                except Exception:
                    pass


async def _warm(ctx, timeout_s: float = 45.0) -> None:
    """Load the homepage once before doing anything else.

    A freshly launched context that navigates STRAIGHT to a search URL is
    refused on that first request and only answers from the second onward
    -- which showed up as the first keyword of every batch silently
    returning nothing while the rest worked.
    """
    page = await ctx.new_page()
    try:
        await page.goto("https://www.tiktok.com/", wait_until="domcontentloaded",
                        timeout=int(timeout_s * 1000))
        await page.wait_for_timeout(5000)
    except Exception as e:
        log.warning(f"tiktok: warm-up failed -- {type(e).__name__}: {e}")
    finally:
        try:
            await page.close()
        except Exception:
            pass


# The Users tab is SERVER-RENDERED. `/api/search/user/full/` fires only
# sometimes; on a normal load the accounts arrive inside the HTML itself
# and no XHR ever carries them. Listening only for that response therefore
# reported zero while ten accounts sat on screen. Reading the cards is also
# the more faithful answer to "show me what TikTok shows": this walks them
# in DOM order, which IS the order TikTok ranked them in.
#
# Each card is an `a[href="/@handle"]` whose innerText is
#   <nickname> \n <handle> \n <n> \n Followers \n · \n <n> \n Likes
# so the counts are read by the label that follows them rather than by
# position -- the same tactic the profile-header parse uses.
JS_USER_CARDS = r"""
() => {
  const out = [];
  const seen = new Set();
  for (const a of document.querySelectorAll('a[href^="/@"]')) {
    const m = (a.getAttribute('href') || '').match(/^\/@([^/?]+)/);
    if (!m) continue;
    const username = m[1];
    if (!username || seen.has(username.toLowerCase())) continue;
    const lines = (a.innerText || '').split('\n').map(s => s.trim()).filter(Boolean);
    // the sidebar's own profile link has no card body; a result always does
    if (lines.length < 2) continue;
    seen.add(username.toLowerCase());
    let followers = '', likes = '';
    for (let i = 1; i < lines.length; i++) {
      if (/^followers$/i.test(lines[i])) followers = lines[i - 1];
      else if (/^likes$/i.test(lines[i])) likes = lines[i - 1];
    }
    const img = a.querySelector('img');
    const nickname = lines[0];   // first line is the display name
    out.push({ username, nickname, followers, likes,
               avatar: img ? (img.getAttribute('src') || '') : '' });
  }
  return out;
}
"""


async def user_cards(page) -> list[TikTokUser]:
    """The Users tab's rendered results, in the order TikTok ranked them."""
    from backend.shared.text import parse_count

    rows = await page.evaluate(JS_USER_CARDS)
    out: list[TikTokUser] = []
    for r in rows or []:
        username = (r.get("username") or "").strip()
        if not username:
            continue
        followers, _ = parse_count(r.get("followers") or "")
        hearts, _ = parse_count(r.get("likes") or "")
        out.append(TikTokUser(
            username=username,
            nickname=(r.get("nickname") or "").strip(),
            avatar=(r.get("avatar") or "").strip(),
            follower_count=followers,
            heart_count=hearts,
            match_kind="account",
        ))
    return out


async def search_users(
    keywords: list[str], proxy: Optional[dict] = None, timeout_s: float = 45.0,
) -> dict[str, list[TikTokUser]]:
    """{keyword: name-matched accounts} from TikTok's Users tab.

    One browser for the whole batch -- the persistent profile is the
    scarce resource, not the page load.
    """
    out: dict[str, list[TikTokUser]] = {kw: [] for kw in keywords}
    if not keywords:
        return out
    try:
        async with anonymous_context(proxy) as ctx:
            for kw in keywords:
                out[kw] = await _users_for(ctx, kw, timeout_s)
                log.info(f"tiktok/users {kw!r}: {len(out[kw])} account(s)")
    except Exception as e:
        log.warning(f"tiktok/users: account search unavailable -- {type(e).__name__}: {e}")
    return out


async def search_users_in(ctx, keywords: list[str], timeout_s: float = 45.0
                          ) -> dict[str, list[TikTokUser]]:
    """`search_users` against a context the caller already owns -- used when
    a sweep is ALREADY running anonymously and must not try to take the
    profile lock a second time (it would deadlock against itself)."""
    out: dict[str, list[TikTokUser]] = {}
    for kw in keywords:
        try:
            out[kw] = await _users_for(ctx, kw, timeout_s)
        except Exception as e:
            log.warning(f"tiktok/users {kw!r}: {type(e).__name__}: {e}")
            out[kw] = []
        log.info(f"tiktok/users {kw!r}: {len(out[kw])} account(s)")
    return out


async def _users_for(ctx, keyword: str, timeout_s: float) -> list[TikTokUser]:
    """One keyword's Users tab, read off `/api/search/user/full/`, scrolled
    to the end of the list the same way the Top tab is."""
    page = await ctx.new_page()
    bodies: list[str] = []

    async def on_response(resp):
        """Collects the Users-tab response bodies. Kept alongside the DOM
        harvest rather than replacing it: the XHR is richer (verified
        flag, exact counts, entity id) but the DOM is what carries
        TikTok's ranking order, so both are read and merged below."""
        if "/api/search/user" not in resp.url:
            return
        try:
            text = await resp.text()
        except Exception:
            return
        if text:
            bodies.append(text)

    page.on("response", lambda r: asyncio.create_task(on_response(r)))
    try:
        await page.goto(USER_SEARCH_URL.format(q=quote(keyword)),
                        wait_until="domcontentloaded", timeout=int(timeout_s * 1000))

        # Poll for the cards themselves rather than sleeping a fixed
        # amount: server-rendered results have been observed taking ~12s
        # to paint, and a 6s sleep read an empty page and reported no
        # accounts at all.
        deadline = time.time() + timeout_s
        while time.time() < deadline:
            if len(await user_cards(page)) >= 1:
                break
            await page.wait_for_timeout(1000)
        else:
            log.info(f"tiktok/users {keyword!r}: no result cards rendered")
            return []
        await page.wait_for_timeout(1500)

        # Ordered accumulator: DOM order IS TikTok's ranking, so keep first
        # sight of each handle and let scrolling append.
        ordered: dict[str, TikTokUser] = {}

        async def harvest() -> int:
            """Absorb whatever cards are currently rendered, keeping FIRST
            sight of each handle -- DOM order is TikTok's own ranking, and
            setdefault preserves it across scrolls. Returns the running
            total, which the scroll loop uses to detect a stall."""
            for u in await user_cards(page):
                ordered.setdefault(u.username.lower(), u)
            return len(ordered)

        await harvest()
        stalls = 0
        for _ in range(25):
            before = len(ordered)
            await page.evaluate(JS_SCROLL_RESULTS)
            await page.wait_for_timeout(2200)
            stalls = stalls + 1 if await harvest() == before else 0
            if stalls >= 4:
                break

        # Fold in anything the XHR did carry -- it is richer (verified
        # flag, exact counts, entity id) -- without disturbing DOM order.
        for text in bodies:
            for blob in parse_lines(text):
                for u in iter_users(blob):
                    key = u.username.lower()
                    u.match_kind = "account"
                    if key in ordered:
                        prev = ordered[key]
                        u.nickname = u.nickname or prev.nickname
                        u.avatar = u.avatar or prev.avatar
                        if u.follower_count is None:
                            u.follower_count = prev.follower_count
                        if u.heart_count is None:
                            u.heart_count = prev.heart_count
                    ordered[key] = u

        return list(ordered.values())
    except Exception as e:
        log.warning(f"tiktok/users {keyword!r}: {type(e).__name__}: {e}")
        return []
    finally:
        try:
            await page.close()
        except Exception:
            pass


@dataclass
class Sweep:
    """WHAT: the result of sweeping one keyword -- the hits, the accounts
    behind them, and WHY the sweep ended. HOW: `stopped` carries the
    reason as a short tag and `complete` is True only when the results
    genuinely ran out, so a caller can tell "nothing more to find" apart
    from "we stopped early"; `source` records whether the values came from
    TikTok's own payloads or from the DOM stand-in, which makes a silent
    slide down the fallback chain visible in the logs. LINKED TO:
    services/discovery_service.py reads these fields; `extraction` is the
    blame-frame report from shared/extraction.py."""

    keyword: str
    tab: str = "people"
    hits: list[Row] = field(default_factory=list)
    users: list[TikTokUser] = field(default_factory=list)
    pages: int = 0
    stopped: str = ""  # exhausted | stalled | cap:* | error
    complete: bool = False
    seconds: float = 0.0
    error: str = ""
    # "hydration+network" normally; "dom" when both came up empty and the
    # rendered results page had to stand in
    source: str = "hydration+network"
    extraction: Optional[ExtractionResult] = None

    @property
    def account_hits(self) -> int:
        """Hits that came from TikTok's own user-card block (a name match
        for the query) rather than from a video's author."""
        return sum(1 for u in self.users if u.match_kind == "account")

    def summary(self) -> str:
        """One-line log form. Reports name-matched accounts SEPARATELY
        from the raw hit count, because a sweep that returns 40 hits of
        which 0 are name matches has found nothing worth triaging, and a
        single total would hide that."""
        base = (f"{len(self.hits)} hits ({self.account_hits} name-matched accounts), "
                f"{self.pages} pages, {self.stopped}")
        return f"{base}, via {self.source}" if self.source != "hydration+network" else base


class Discovery:
    """WHAT: keywords in, candidate accounts out. HOW: runs sweeps on an
    already-started browser context, reading TikTok's own search payloads
    first and falling back to the rendered results page only when those
    come up empty.

    LINKED TO: `discovery_path` in backend/platforms/registry.py names
    this class, and services/discovery_service.py drives it. The context
    is passed IN rather than created here so one browser can serve a whole
    multi-keyword run."""

    def __init__(self, args, ctx, anonymous: bool = False):
        """`ctx` is an already-started browser context. `anonymous` says it
        is the persistent credential-free one, which changes how the
        Users-tab pass acquires it (see _merge_user_accounts)."""
        self.a = args
        self.ctx = ctx
        # True when `ctx` is ALREADY the anonymous persistent context. The
        # Users-tab pass must then reuse it rather than opening its own,
        # which would block forever on a profile lock this same task holds.
        self.anonymous = anonymous
        # the logged-in handle, learned per sweep from the page itself
        self._viewer = ""

    async def sweep(self, keyword: str, tab: str = "people") -> Sweep:
        """WHAT: one keyword -> a Sweep of candidate accounts. HOW: opens
        the search page and intercepts the /api/search/ responses it
        fires, since those carry richer records (verified flag, exact
        counts, entity id) than anything the DOM renders. Scrolls to pull
        further pages, then folds in the Users tab via
        _merge_user_accounts so genuine NAME matches rank ahead of people
        who merely posted a matching video.

        The viewer's own handle is removed: every rendered TikTok page
        embeds the logged-in account, and without that filter the
        session's own profile was collected as an impersonator of every
        keyword on every sweep (see viewer_username). LINKED TO:
        `user_to_row` builds the shared Row; iter_users and
        parse_lines above do the payload work."""
        out = Sweep(keyword=keyword, tab=tab)
        started = time.time()
        page = await self.ctx.new_page()

        by_username: dict[str, TikTokUser] = {}
        arrived = asyncio.Event()

        async def on_response(resp):
            """Absorbs every search payload the page fires, keeping FIRST
            sight of each handle -- iter_users already yields name matches
            ahead of video authors, so setdefault preserves that
            precedence. Signals `arrived` so the sweep can stop waiting as
            soon as real data lands instead of sleeping a fixed time."""
            try:
                if "/api/search/" not in resp.url:
                    return
                text = await resp.text()
            except Exception:
                return
            for blob in parse_lines(text):
                for u in iter_users(blob):
                    by_username.setdefault(u.username.lower(), u)
            out.pages += 1
            arrived.set()

        page.on("response", lambda r: asyncio.create_task(on_response(r)))

        try:
            await page.goto(
                SEARCH_URL.format(q=quote(keyword)), wait_until="domcontentloaded",
                timeout=self.a.timeout * 1000,
            )

            # Blocked region? Stop here and NAME it. Everything below would
            # otherwise run its full time budget against a notice page and
            # report a stall (see RE_GEOBLOCK).
            body = await _body_text(page)
            if geoblocked(page.url, body):
                out.stopped, out.complete = "geoblocked", False
                out.error = (
                    "TikTok is blocked for this IP -- the request was redirected to "
                    f"{page.url}. Route this platform through a proxy in a region "
                    "where TikTok is available."
                )
                log.warning(f"tiktok/people {keyword!r}: {out.error}")
                out.seconds = time.time() - started
                return out

            # A CAPTCHA/slide-verify challenge instead of results -- same
            # signal analysis_engine.py::Scraper.process() already checks
            # for (RE_CHECKPOINT / "/captcha" in the URL), just missing
            # here. Without this, a checkpointed session's search page
            # renders no results and the sweep below eventually gives up
            # via the ordinary "stalled" path, which looks identical to a
            # slow page and never tells `sessions/manager.py` the session
            # itself is the problem -- so the same checkpointed session
            # keeps getting handed out to the next job.
            if RE_CHECKPOINT.search(body) or "/captcha" in page.url:
                out.stopped, out.complete = "checkpoint", False
                out.error = (
                    "TikTok served a CAPTCHA/verification challenge instead of "
                    "search results -- this session is checkpointed."
                )
                log.warning(f"tiktok/people {keyword!r}: {out.error}")
                out.seconds = time.time() - started
                return out

            # Wait for the search tab strip itself, not for a body-text
            # length: `#search-tabs` only mounts once the results view has
            # actually rendered, whereas innerText clears 400 characters
            # from the chrome (nav, footer, cookie banner) alone, on a page
            # that has no results on it yet. Falling through early is what
            # made the first read land before the results existed.
            try:
                await page.wait_for_selector("#search-tabs button", timeout=self.a.settle * 1000)
            except Exception:
                log.warning(f"tiktok/people {keyword!r}: search results never rendered")

            # Deliberately NOT switching to the Users tab -- see the block
            # above SEARCH_URL. The Top tab is the one that answers.

            # The first batch of results may already be in the hydration
            # payload embedded at load, try it before waiting on any XHR,
            # same reasoning as the profile page (see module docstring).
            hydration = await read_hydration(page)
            if hydration:
                self._viewer = viewer_username(hydration).lower()
                for u in iter_users(hydration):
                    by_username.setdefault(u.username.lower(), u)

            if not by_username:
                try:
                    await asyncio.wait_for(arrived.wait(), timeout=self.a.settle)
                except asyncio.TimeoutError:
                    pass

            stalls = 0
            while True:
                if self.a.max_results and len(by_username) >= self.a.max_results:
                    out.stopped = "cap:results"
                    break
                if self.a.max_pages and out.pages >= self.a.max_pages:
                    out.stopped = "cap:pages"
                    break
                if self.a.max_seconds and time.time() - started >= self.a.max_seconds:
                    out.stopped = "cap:seconds"
                    break

                before = len(by_username)
                arrived.clear()
                await page.evaluate(JS_SCROLL_RESULTS)
                try:
                    await asyncio.wait_for(arrived.wait(), timeout=self.a.page_wait)
                except asyncio.TimeoutError:
                    pass

                if len(by_username) > before:
                    stalls = 0
                    if out.pages and out.pages % self.a.progress_every == 0:
                        print(
                            f"    [tiktok/{tab}] {keyword!r}: {len(by_username)} so far, "
                            f"page {out.pages}, {time.time()-started:.0f}s",
                            file=sys.stderr,
                        )
                else:
                    stalls += 1
                    if stalls >= self.a.patience:
                        # A CAPTCHA can also appear mid-scroll (bot
                        # detection tripping after several requests), not
                        # just on the initial load -- check once more
                        # before writing this off as an ordinary stall.
                        stall_body = await _body_text(page)
                        if RE_CHECKPOINT.search(stall_body) or "/captcha" in page.url:
                            out.stopped, out.complete = "checkpoint", False
                            out.error = (
                                "TikTok served a CAPTCHA/verification challenge mid-sweep -- "
                                "this session is checkpointed."
                            )
                            log.warning(f"tiktok/people {keyword!r}: {out.error}")
                        else:
                            out.stopped, out.complete = "stalled", False
                        break
                    await page.wait_for_timeout(600)

            # Hydration + intercepted network first (richer, real counts).
            # Rendered DOM second, only when both produced nothing at all:
            # a healthy sweep never pays for the DOM pass, and when
            # TikTok's payload shape rotates, discovery degrades to "fewer
            # fields" instead of to "zero results, reported as success".
            chain = await run_strategies(
                f"tiktok/search[{keyword!r}]",
                [
                    ("hydration+network", lambda: list(by_username.values())),
                    ("dom:profile-links", lambda: dom_users(page)),
                ],
            )
            users = chain.value or []
            out.extraction = chain
            if chain.degraded:
                out.source = "dom"

            # Drop the logged-in account (see viewer_username) and put
            # TikTok's own name matches ahead of incidental video authors,
            # so `rank` -- and therefore the order an analyst works through
            # the cards in -- leads with the actual impersonation
            # candidates. Stable within each group: TikTok's own relevance
            # ordering is preserved, only the two groups are separated.
            viewer = getattr(self, "_viewer", "")
            users = [u for u in users if u.username.lower() != viewer]
            out.users = sorted(users, key=lambda u: u.match_kind != "account")

            # "search:account" == TikTok returned this as a name match for
            # the keyword; "search:author" == it merely posted a video the
            # keyword matched. Stored as the profile's discovery_source so
            # the difference survives into triage instead of being
            # flattened away.
            out.hits = [
                user_to_row(
                    u, keyword,
                    source=out.source if out.source == "dom" else f"search:{u.match_kind}",
                )
                for u in out.users
                if u.url
            ]
            # TikTok's Users tab, which this Top-tab sweep structurally
            # cannot see (video items, not accounts). Merged here rather
            # than in run(): the discovery service drives sweep() directly
            # per (keyword, tab) and never calls run(), so anything hung
            # off run() is dead code in production.
            await self._merge_user_accounts(out)

            if self.a.max_results:
                out.hits = out.hits[: self.a.max_results]
        except Exception as e:
            out.stopped, out.error = "error", f"{type(e).__name__}: {e}"
        finally:
            try:
                await page.close()
            except Exception:
                pass
            out.seconds = time.time() - started
        return out

    async def _merge_user_accounts(self, out: "Sweep") -> None:
        """Fold the Users-tab accounts into this sweep, ahead of the video
        authors. Best-effort: a failure here leaves the Top-tab results
        exactly as they were."""
        try:
            if self.anonymous:
                # This task already owns the profile lock (the whole sweep
                # is running inside anonymous_context), so reuse that
                # context -- taking the lock again would deadlock.
                found = (await search_users_in(self.ctx, [out.keyword])).get(out.keyword) or []
            else:
                # search_users takes the lock itself, via anonymous_context
                found = (await search_users(
                    [out.keyword], proxy=getattr(self.a, "proxy", None),
                )).get(out.keyword) or []
        except Exception as e:
            log.warning(f"tiktok/users {out.keyword!r}: skipped -- {type(e).__name__}: {e}")
            return
        if not found:
            return

        names = {u.username.lower() for u in found}
        out.users = found + [u for u in out.users if u.username.lower() not in names]
        out.hits = [
            user_to_row(
                u, out.keyword,
                source=out.source if out.source == "dom" else f"search:{u.match_kind}",
            )
            for u in out.users
            if u.url
        ]

    async def run(self, keywords: list[str], tabs: Optional[list[str]] = None) -> list[Sweep]:
        """WHAT: sweeps a whole list of keywords. HOW: concurrently up to
        the configured limit, with a staggered start so several browser
        tabs do not hit TikTok in the same instant, and results re-sorted
        back into the caller's keyword order (which `gather` does not
        guarantee). `tabs` is accepted and ignored: TikTok has one
        people-search surface, and the parameter exists so every
        platform's Discovery.run has the same signature. LINKED TO: the
        standalone entry point; the API path drives sweep() per keyword
        through services/discovery_service.py instead."""
        sem = asyncio.Semaphore(max(1, self.a.concurrency))

        async def one(i: int, keyword: str) -> tuple[int, Sweep]:
            """One keyword, holding a concurrency slot for its duration."""
            async with sem:
                await asyncio.sleep(i % max(1, self.a.concurrency) * 1.0)
                s = await self.sweep(keyword)
                print(
                    f"  [tiktok/people] {keyword!r}: {s.summary()} ({s.seconds:.1f}s)",
                    file=sys.stderr,
                )
                return i, s

        pairs = await asyncio.gather(*(one(i, k) for i, k in enumerate(keywords)))
        return [s for _, s in sorted(pairs, key=lambda p: p[0])]
